### ISSUE TITLE
need ACL support for basic authentication middleware

### ISSUE THREAD

**Issue by missedone** [ant0ine/go-json-rest#112]
Hi ant0ine

go-json-rest is quite well that help me quickly get my simple restful service working, i added basic auth middleware to the restful interfaces.
now i want to add ACL support so that, for example, only Admin can have POST/PUT/DELET privileges while User can only GET.
but the Authenticator signature: `Authenticator: func(userId string, password string) bool`, only pass the user name and password while i want more context, e.g. Method, URI, etc.

so i think we can simple pass one more parameter `request *Request` to it: `Authenticator: func(userId string, password string, request *Request) bool` (I copied the auth_basic.go and modify it to fit my ACL need locally), but i think this could be common if people need ACL support.

**Comment by ant0ine** [comment]
Thinking more about this, I think it would be nice to dissociate the two steps:
1) Authentication
2) Authorization
Once the users are known, check their permissions for this given request.
We could add an optional callback to this middleware like this:
```go
        Authorizator func(userId string, request *Request) bool
```
The will be executed after a successful call to `Authenticator`.

This has the benefit to be backward compatible. But the authorization is still required for all requests.

**Comment by missedone** [comment]
Hi Antoine

agreed, that's the right approach, authorization will proceed only if the
callback is injected.



  Thanks & Best Regards!

                  ///
                 (. .)
  --------ooO--(_)--Ooo--------
  |           Nick Tan           |
  ------------------------------------

**Comment by ant0ine** [comment]
@missedone The PR is there: https://github.com/ant0ine/go-json-rest/pull/122 I'll merge that soon.

**Comment by missedone** [comment]
@ant0ine that looks good to me, thanks:)

**Comment by ant0ine** [comment]
merged, closing this issue.
