### ISSUE TITLE
Can't parse time format from encoding/json package

### ISSUE THREAD

**Issue by jheroy** [ant0ine/go-json-rest#117]
encoding/json time format: 2014-05-16T08:28:06.801064Z
rest time format:2014-05-16T08:28:06Z

**Comment by ant0ine** [comment]
Hi @jheroy ! Is it still an issue ?

**Comment by jheroy** [comment]
Yes

**Comment by ant0ine** [comment]
This package does not change the behavior of the standard lib encoding/json. It just calls json.Marshal(...)
At best, what we can provide is an example with datetime in the payload.
