### ISSUE TITLE
Json marshal not handle "json" tag field

### ISSUE THREAD

**Issue by jheroy** [ant0ine/go-json-rest#118]
type Test struct {
     A int   `json:"-"`
     B string  `json:"b"`
}
I want rename B to b and delete A in json doc, but rest's json marshal not support it.

**Comment by yannk** [comment]
I don't think go-json-rest does anything fancy in terms of json marshaling it pretty much delegates to the standard package. Can you provide a test case?

**Comment by jheroy** [comment]
This is my struct define:
``` go
type AgentServer struct {

	Id       T_server_id
	Name     string
	ChatRoom string `json:"-"`
	ChatIp   string `json:"-"`
	ChatPort string `json:"-"`
	Status   string
	OpenTime time.Time
}
```
encoding/json package output:
``` json
{"Id": 1001, "Name": "Test", "Status":"online", "OpentTime":""}
```
but rest json output:
``` json
{"Id":1001, "Name":"Test", "ChatRoom": "", "ChatIp","", "ChatPort": "", "Status":"online", "OpenTime": "0001/01/01T00:00:00Z"}
```

**Comment by jheroy** [comment]
Sorry, My mistake
