### ISSUE TITLE
Example of setting a cookie with rest.ResponseWriter

### ISSUE THREAD

**Issue by mark-anders** [ant0ine/go-json-rest#124]
How does one call the http.SetCookie method with the rest.ResponseWriter object provided to a handler?     Attempting to call directly gives: 

       "rest.ResponseWriter does not implement http.ResponseWriter (missing Write method)"

**Comment by yannk** [comment]
You probably need a type assertion http://golang.org/ref/spec#Type_assertions Please post a (ideally runnable on play.golang.org) snippet of your code.

**Comment by ant0ine** [comment]
Hi,

The provided implementation of rest.ResponseWriter also implement other interfaces, from the code:
```go
// ResponseWriter
// http.ResponseWriter
// http.Flusher
// http.CloseNotifier
// http.Hijacker
```
so you need to do:
```go
writer := w.(http.ResponseWriter)
http.SetCookie(writer, cookie)
```

**Comment by ant0ine** [comment]
Right, what @yannk said, a type assertion.

**Comment by mark-anders** [comment]
That did it... Thanks!
