### ISSUE TITLE
V3 version's log support seems trigger panic at runtime

### ISSUE THREAD

**Issue by hxiaodon** [ant0ine/go-json-rest#126]
Hi,
When I prepare to migrate from V2 to V3, I found that the restful framework will trigger panic at runtime

My partial code:

	var logErr error
	restLog, logErr := os.OpenFile("./log/rest_access.log", os.O_CREATE|os.O_APPEND|os.O_RDWR, 0660)
	if logErr != nil {
		panic(logErr)
	}
	defer restLog.Close()
	restErrLog, logErr := os.OpenFile("./log/rest_error.log", os.O_CREATE|os.O_APPEND|os.O_RDWR, 0660)
	if logErr != nil {
		panic(logErr)
	}
	defer restErrLog.Close()

	api := rest.NewApi()
	statusMw := &rest.StatusMiddleware{}
	api.Use(statusMw)
	api.Use(rest.DefaultProdStack...)

	api.Use(&rest.TimerMiddleware{})
	api.Use(&rest.RecorderMiddleware{})

	//access log
	api.Use(&rest.AccessLogApacheMiddleware{
		Logger: log.New(restLog, "", 0),
	})
	//error log
	api.Use(&rest.RecoverMiddleware{
		Logger: log.New(restErrLog, "", log.Ldate|log.Ltime|log.Llongfile),
		EnableResponseStackTrace: true,
	}) 

And the backtrace info is below:

interface conversion: interface is nil, not int
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/recover.go:41 (0x448def)
        func.018: trace := debug.Stack()
c:/go/src/runtime/asm_amd64.s:401 (0x426e1c)
c:/go/src/runtime/panic.go:387 (0x413a0f)
c:/go/src/text/template/exec.go:100 (0x4ae593)
c:/go/src/runtime/asm_amd64.s:401 (0x426e1c)
c:/go/src/runtime/panic.go:387 (0x413a0f)
c:/go/src/runtime/iface.go:222 (0x40c2f5)
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/access_log_apache.go:203 (0x441bbb)
        (*accessLogUtil).StatusCode: return u.R.Env["STATUS_CODE"].(int)
c:/go/src/runtime/asm_amd64.s:401 (0x426e1c)
c:/go/src/reflect/value.go:419 (0x5b005c)
c:/go/src/reflect/value.go:296 (0x5aee53)
c:/go/src/text/template/exec.go:567 (0x4b556b)
c:/go/src/text/template/exec.go:478 (0x4b3e32)
c:/go/src/text/template/exec.go:449 (0x4b36c4)
c:/go/src/text/template/exec.go:416 (0x4b2bad)
c:/go/src/text/template/exec.go:354 (0x4b2390)
c:/go/src/text/template/exec.go:332 (0x4b12af)
c:/go/src/text/template/exec.go:167 (0x4af3fc)
c:/go/src/text/template/exec.go:175 (0x4afb19)
c:/go/src/text/template/exec.go:155 (0x4aec89)
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/access_log_apache.go:156 (0x44162d)
        (*AccessLogApacheMiddleware).executeTextTemplate: err := mw.textTemplate.Execute(buf, util)
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/access_log_apache.go:91 (0x447bfa)
        func.001: mw.Logger.Print(mw.executeTextTemplate(util))
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/recorder.go:22 (0x448c05)
        func.017: h(writer, r)
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/timer.go:20 (0x449730)
        func.022: h(w, r)
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/content_type_checker.go:38 (0x448573)
        func.010: handler(w, r)
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/gzip.go:25 (0x4486ee)
        func.012: h(writer, r)
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/recover.go:57 (0x44909e)
        func.019: h(w, r)
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/powered_by.go:26 (0x448b23)
        func.016: h(w, r)
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/recorder.go:22 (0x448c05)
        func.017: h(writer, r)
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/timer.go:20 (0x449730)
        func.022: h(w, r)
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/access_log_apache.go:87 (0x447b6c)
        func.001: h(w, r)
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/status.go:32 (0x449264)
        func.021: h(w, r)
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/middleware.go:70 (0x448a27)
        func.015: handler(writer, request)
c:/go/src/net/http/server.go:1265 (0x461cd8)
c:/go/src/net/http/server.go:1703 (0x463da1)
c:/go/src/net/http/server.go:1204 (0x46180e)
c:/go/src/runtime/asm_amd64.s:2232 (0x428f61)
127.0.0.1 - - 13/Feb/2015:16:46:47 +0800 "GET /countries HTTP/1.1" 500 33 "-" "curl/7.39.0"\

The type assertion seems to be the root cause, u.R.Env["STATUS_CODE"] is nil when I involved the logging feature.
D:/GoPath/src/github.com/ant0ine/go-json-rest/rest/access_log_apache.go:203 (0x441bbb)
        (*accessLogUtil).StatusCode: return u.R.Env["STATUS_CODE"].(int)

Could you help to fix it?
Thanks!

**Comment by hxiaodon** [comment]
I'm not sure why the R.Env["STATUS_CODE"] is nil when enabling log feature. although initially I have a draft plan to use the safe type assertion, but I suspect that the http status code will be an incorrect one when writing into log

**Comment by ant0ine** [comment]
Hi,

Thanks for the bug report! At first sight, it seems to be an incorrect order in the middlewares, or a duplicate middleware, or both. Anyway, I think if the failure is legit, it should fail in a more elegant way.
I'll take a look at it this week end.

Antoine

**Comment by ant0ine** [comment]
Alright, I confirmed this is due to middleware that are duplicated and in the wrong order.
``` go
api.Use(rest.DefaultProdStack...)
```
already inludes for you the following:
``` go
var DefaultProdStack = []Middleware{
        &AccessLogApacheMiddleware{
                Format: CombinedLogFormat,
        },
        &TimerMiddleware{},
        &RecorderMiddleware{},
        &PoweredByMiddleware{},
        &RecoverMiddleware{},
        &GzipMiddleware{},
        &ContentTypeCheckerMiddleware{},
}
```

So, your `Use` of AccessLogApacheMiddleware, TimerMiddleware, and RecorderMiddleware is redundant.
Also, the order is not correct, AccessLogApacheMiddleware depend on the data collected by TimerMiddleware, and RecorderMiddleware. So, they should be part of the wrapped handlers.

I suggest you don't use `DefaultProdStack` and instead make your own custom stack:

``` go
api := rest.NewApi()
statusMw := &rest.StatusMiddleware{}
api.Use(statusMw)
api.Use(&rest.AccessLogApacheMiddleware{
    Logger: log.New(restLog, "", 0),
})
api.Use(&rest.TimerMiddleware{})
api.Use(&rest.RecorderMiddleware{})
api.Use(&rest.RecoverMiddleware{
    Logger: log.New(restErrLog, "", log.Ldate|log.Ltime|log.Llongfile),
    EnableResponseStackTrace: true,
}) 
```

Now, regarding the possible improvements to make in Go-Json-Rest to make it fail in a more elegant way: We could have AccessLogApacheMiddleware skipping the missing values instead of failing. not sure which one is best.

**Comment by ant0ine** [comment]
OK, this change will make AccessLogApacheMiddleware work even in Timer and Recorder are not wrapped. It becomes marginally useful in that case, you should still have Timer and Recorder in the wrapped middlewares if you want to log something useful.
https://github.com/ant0ine/go-json-rest/commit/37c3e6775decdfca6643bc1775839f9de629ded5

**Comment by hxiaodon** [comment]
Awesome work! Thanks for your kindly and quickly support:)
