### ISSUE TITLE
custom middleware and status middleware getting panic

### ISSUE THREAD

**Issue by tvmaly** [ant0ine/go-json-rest#128]
I am using the status middleware.  I also am using a custom middleware that checks for json web token in header for certain paths and throws rest Error if not found.   I get a http panic in this case.  If I remove the status middleware, the panic goes away.

http: panic serving 127.0.0.1:51211: interface conversion: interface is nil, not int
goroutine 6 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xa8
github.com/ant0ine/go-json-rest/rest.func·021(0xb75102a0, 0x1867a6b0, 0x1867a6a0)
	/home/tmaly/godev/src/github.com/ant0ine/go-json-rest/rest/status.go:34 +0xaf
github.com/ant0ine/go-json-rest/rest.func·015(0xb7510280, 0x1865cbd0, 0x1865cb60)
	/home/tmaly/godev/src/github.com/ant0ine/go-json-rest/rest/middleware.go:70 +0x111
net/http.HandlerFunc.ServeHTTP(0x1860a668, 0xb7510280, 0x1865cbd0, 0x1865cb60)
	/usr/local/go/src/net/http/server.go:1265 +0x3b
net/http.serverHandler.ServeHTTP(0x18632700, 0xb7510280, 0x1865cbd0, 0x1865cb60)
	/usr/local/go/src/net/http/server.go:1703 +0x145
net/http.(*conn).serve(0x1864a120)
	/usr/local/go/src/net/http/server.go:1204 +0x9d8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x2ce

**Comment by ant0ine** [comment]
Hi,

I think you may be missing the TimerMiddleware and the RecorderMiddleware that must be included in the Middlewares wrapped by StatusMiddleware.

Timer and Recorder keep track of information about the request/response, and put them in the Env. Then the StatusMiddleware computes stats using this information.

See documentation here: https://godoc.org/github.com/ant0ine/go-json-rest/rest#StatusMiddleware

Also, I agree that a "panic" like this one is not a user friendly message, I'll change that with a proper error message that mentions the Timer and Recorder Middlewares.

**Comment by ant0ine** [comment]
Added this https://github.com/ant0ine/go-json-rest/commit/f4c47777dd0f683a9cc387e626e02a736853bfad You should get a better error message now.

**Comment by tvmaly** [comment]
Thanks,  I will test it this week
