### ISSUE TITLE
why am i getting empty response?

### ISSUE THREAD

**Issue by john-qin** [ant0ine/go-json-rest#131]
I was expecting to get a json success message back. but when I test the code using restful client. I got an empty response {}.  couldn't figure out whats wrong with code.

func main() {

	api := rest.NewApi()
	api.Use(rest.DefaultDevStack...)
	router, err := rest.MakeRouter(
		&rest.Route{"POST", "/autoMigrate", AutoMigrate},
	)

	if err != nil {
		log.Fatal(err)
	}

	api.SetApp(router)
	log.Fatal(http.ListenAndServe(":8081", api.MakeHandler()))

}

type Response struct {
	success bool
	message string
}

func AutoMigrate(w rest.ResponseWriter, r *rest.Request) {
	response := Response{success: true, message: ""}
	w.WriteJson(&response)
}

**Comment by yannk** [comment]
Your Response struct only has private field (lower case). This should work:

```
func main() {

api := rest.NewApi()
api.Use(rest.DefaultDevStack...)
router, err := rest.MakeRouter(
    &rest.Route{"POST", "/autoMigrate", AutoMigrate},
)

if err != nil {
    log.Fatal(err)
}

api.SetApp(router)
log.Fatal(http.ListenAndServe(":8081", api.MakeHandler()))
}

type Response struct {
success bool
message string
}

func AutoMigrate(w rest.ResponseWriter, r *rest.Request) {
response := Response{success: true, message: ""}
w.WriteJson(&response)
}
```

**Comment by john-qin** [comment]
yannk, thank you so much.  still a go newbie. got it working now.
