### ISSUE TITLE
It may be more clear to change from func MakeRouter(routes ...*Route)  change to func MakeRouter(routes []*Route)  

### ISSUE THREAD

**Issue by benluo** [ant0ine/go-json-rest#132]
I tried to change from func MakeRouter(routes ...*Route)  change to func MakeRouter(routes []*Route).
Then I can use a slice in separate file like
 
```golang
// routes.go
package main

import (
	"github.com/ant0ine/go-json-rest/rest"
)

var routes = []*rest.Route{
	&rest.Route{"GET", "/reminders", GetAllReminders},
}
```

in main.go file change to 

```golang
router, err := rest.MakeRouter(routes)
```

I also tried to change your gzip_test.go with positive result.

**Comment by ant0ine** [comment]
Hi,

The benefit of the *variadic* (...) function is that the syntax feels much lighter, no need to declare the slice of type `*Route`.

Also, changing this would be a breaking change, which is done only for major version of this framework (following http://semver.org/)

Antoine

**Comment by benluo** [comment]
it makes main.go longer and longer if there are more routes to be handled.

Best regards,

Ben Luo

**Comment by ant0ine** [comment]
Note that you can use the slice that you defined like this:

```go
var routes = []*rest.Route{
    &rest.Route{"GET", "/reminders", GetAllReminders},
}
router, err := rest.MakeRouter(routes...)
```

**Comment by benluo** [comment]
It works, cool.

Best regards,

Ben Luo
