### ISSUE TITLE
using PathParam from middleware

### ISSUE THREAD

**Issue by iwanbk** [ant0ine/go-json-rest#134]
I have created a middleware and it can't access PathParam.
The docs also said so https://github.com/ant0ine/go-json-rest/blob/master/rest/handler.go#L45.

If it is not the case, how to access it?

One of example in readme.md show that we can use PathParam from middleware, but it can't be build.

**Comment by ant0ine** [comment]
Hi @iwanbk 

First, note that the object ResourceHandler is deprecated. It's going to be removed from the code at the end of the deprecation cycle.

PathParam are available only after the path routing step. The router is in charge of parsing the paths, extracting the parameters, finding the right route, and running the handler corresponding to this route. Until then, the path parameters are not available.

It is possible to create middlewares that access the path parameters, but in that case, they will be used after the routing, as wrapper around the router handlers.

Antoine
