### ISSUE TITLE
Excluding certain path from Middleware handling

### ISSUE THREAD

**Issue by amosshapira** [ant0ine/go-json-rest#135]
I'm working on a user database REST API using go-json-rest and authentication using JWT from https://github.com/StephanDollberg/go-json-rest-middleware-jwt.

Users register with "POST /user". They should be able to do so without being authenticated.
But the middleware intercepts the request and fails it.

So far the only ways I can think of to work around this are:

1. Route the registration call under another path which is handled by a separate App (which doesn't setup the JWT middleware)
1. Wrap, or re-implement the JWT middleware to allow "POST /user" through without authentication.

Both look ugly - the first because it breaks the RESTful principles as I understand them and the second because it basically means that I replicate most of the functionality of an existing package.

Is there a better way to achieve what I need?

Thanks.

**Comment by amosshapira** [comment]
I found the WrapMiddlewares middleware (https://github.com/yannk/go-json-rest/blob/master/rest/middleware.go#L15), and it claims to "This can be used to wrap a set of middlewares, post routing, on a per Route basis.", which sounds like what I need, but I so far I didn't understand how to use it. I'm trying to understand the function's code and the test in https://github.com/ant0ine/go-json-rest/blob/master/rest/middleware_test.go

**Comment by ant0ine** [comment]
Hi  @amosshapira 

You may want to look at this example: https://github.com/ant0ine/go-json-rest#jwt
It works by creating two different Api object, one with auth, and one without.

Antoine

**Comment by amosshapira** [comment]
Thanks @ant0ine,

I'm aware of this example (that's where I started my code from), but the problem with this solution is that it relies on the two Api objects serving two different root's, i.e. the "unauthenticated" paths are served directly under "/" and the "authenticated" paths are served under "/api". I'd like to serve an unauthenticated path+method combination under "/api" (in the context of that example), while the other combinations still require authentication.

**Comment by ant0ine** [comment]
I think you're right, this is a common use case, and it deserves a better solution than the two Api objects.

One solution is to not use the Auth middleware in the stack of middlewares, and to wrap every single route handler with the Auth middleware MiddlewareFunc. Every single route except your POST /user.
=> This solves you /api path issue, but this is really not elegant. The framework should provide something better.

I'm thinking that Auth middlewares could have an additional callback parameter. What about something like that ?

``` go
mw := &AuthBasicMiddleware{
        Realm: "foo",
        PassThrough: func(r *Request) bool {
            if r.URL.Path == "/user" && r.Method == "POST" {
                return true
            }
            return false
        },
        Authenticator: func(userId string, password string) bool { ... },
}

```

**Comment by ant0ine** [comment]
Actually PassThrough is probably not a good name, as it may suggest that all request will go through this. Any suggestion ?

**Comment by amosshapira** [comment]
Perhaps "Override"?

**Comment by amosshapira** [comment]
Both for curiosity's sake and trying to learn my way around (this is my first Go project), could you give a concrete example of what you mean by "wrap every single route handler with the Auth middleware MiddlewareFunc."?

**Comment by ant0ine** [comment]
Or maybe this can be turned into something more generic, like a IfMiddleware:

```go
 type IfMiddleware struct {
    Expression func(r *Request) bool
    IfTrue Middleware
    IfFalse Middleware
}
```

**Comment by ant0ine** [comment]
Re example of wrapping route handler:
https://github.com/ant0ine/go-json-rest#status-auth

You can see that only "/.status" has authentication.

**Comment by amosshapira** [comment]
I prefer generic solutions - they tend to be more future-proof (e.g. allow different authentication paths based on other data, e.g. user history, source ip, MFA for specific operations etc, god knows what people will need in the future).
But I'm still trying to wrap my head around how exactly this would be used.

**Comment by amosshapira** [comment]
Just reporting back that for now your second proposed solution works for me:
```
	jwt_middleware := jwt.JWTMiddleware{
...
        (code from top of main() in https://github.com/ant0ine/go-json-rest#jwt)
        }
...
        removed "main_api.use(&jwt_middleware)"
	main_api_router, _ := rest.MakeRouter(
		&rest.Route{"GET", "/auth_test", handle_auth},
		&rest.Route{"GET", "/refresh_token", jwt_middleware.RefreshHandler},
		&rest.Route{"GET", "/user", jwt_middleware.MiddlewareFunc(handle_get_user)},
		&rest.Route{"POST", "/user", handle_post_user},
...
       )
```
allows me to POST to /user without authentication but requires me to authenticate properly for other paths as well as "GET /user", just what I wanted.
I'd still be looking forward to help test whatever you come up with to make it a little more elegant.
If you'd like to make an example out of this then I'll try to make it such and create a PR.

Thanks.

**Comment by amosshapira** [comment]
Thinking more about the options overnight, and at the risk of over-engineering this, here is another way to make it more generic:

First where I got the idea from: In Vagrant, there is the concept of "Override" (http://docs.vagrantup.com/v2/providers/configuration.html, last section), it allows a per-provider configuration override of global configuration parameters. The override basically means that the global setting is different only when used by the specific Provider. (The document discourages using Overrides but this is because of issues related to the different problem domain and I think they are not relevant arguments here.)

In the same way, mapping "Provider" to "Route" and "Global Settings" to "Api", a Route can override various things about the App with settings which are only used for the specific route, keeping most of the global configuration but giving an opportunity to tweak small things just for a specific route.

This way, a Route() call could pass an additional option "override" function reference which can remove/replace/insert-before/insert-after/add Middlewares to the stack. This also opens up the way to set other things differently for specific routes.

An implementation could be:

1. An optional "Override" parameters.
1. Each Route has its own stack of Middlewares, by default it points to the global one.
1. If Override is provided, then it's a reference to a function which is called with a *copy* of the global Middlewares stack. It modifies it as it sees fit. This happens only when the API is setup so it's not expensive.
1. To help the Override function do its job, provide utility functions to do things like "remove middleware", "replace middleware", "insert before middleware", "append after middleware". Middlewares are referenced by their objects or perhaps their Type.

**Comment by ant0ine** [comment]
@amosshapira I'm glad the second solution works for you, even if not very elegant. I'll work on something better (I'm tempted by the IfMiddleware) and I'll let you know so you can try it. If you like it and want to provide a better example than what we have right now, a PR will be awesome !

Re customizing the stack of middleware per route: This is interesting. Adding middleware to the stack is easy, and doable today (see the WrapMiddleware function). Modifying the stack will be more complicated. I need to think more about that.

Thanks.

Antoine

**Comment by ant0ine** [comment]
Here is the **IfMiddleware** idea written more formally: https://github.com/ant0ine/go-json-rest/pull/136

This is far from being a new idea, @miyagawa wrote something similar for Plack years ago:
http://search.cpan.org/~miyagawa/Plack-1.0034/lib/Plack/Middleware/Conditional.pm

I'll come back to this later this week, see if the `IfFalse` is really useful, write the unit tests, and merge.

Antoine

**Comment by benluo** [comment]
Does it like decorate function in python?

**Comment by amosshapira** [comment]
Sorry for showing my ignorance, but how can I use the branch in my code in order to rest it?
I have the git repo cloned locally on my laptop, and the "ifMiddleware" branch checked out, but I didn't find a way to use it in my code.

**Comment by ant0ine** [comment]
@amosshapira I've changed the status-auth example to use it, just as a way to test. (It probably not a good use case, the jwt would be better)

but just to demonstrate:

```go
func main() {
        api := rest.NewApi()
        statusMw := &rest.StatusMiddleware{}
        api.Use(statusMw)
        api.Use(rest.DefaultDevStack...)
        auth := &rest.AuthBasicMiddleware{
                Realm: "test zone",
                Authenticator: func(userId string, password string) bool {
                        if userId == "admin" && password == "admin" {
                                return true
                        }
                        return false
                },
        }

        api.Use(&rest.IfMiddleware{
                Condition: func(r *rest.Request) bool {
                        if r.URL.Path == "/.status" {
                                return true
                        }
                        return false
                },
                IfTrue: auth,
        })

        router, err := rest.MakeRouter(
                &rest.Route{"GET", "/countries", GetAllCountries},
                &rest.Route{"GET", "/.status",
                        func(w rest.ResponseWriter, r *rest.Request) {
                                w.WriteJson(statusMw.GetStatus())
                        },
                },
        )
        if err != nil {
                log.Fatal(err)
        }
        api.SetApp(router)
        log.Fatal(http.ListenAndServe(":8080", api.MakeHandler()))
}
```

**Comment by ant0ine** [comment]
The **IfMiddleware** has been merged: https://github.com/ant0ine/go-json-rest/pull/136

**Comment by ant0ine** [comment]
Cc @StephanDollberg 
The IfMiddleware fits very well with the JWTMiddleware use case, allowing to use it with a single `Api` object instead of two.

**Comment by StephanDollberg** [comment]
Yes, this is very work. Got asked the same question. I will update the example in `go-json-rest-examples`.

**Comment by ant0ine** [comment]
Thanks @StephanDollberg !
