### ISSUE TITLE
API Versioning example not work when use api.Use method

### ISSUE THREAD

**Issue by wingyplus** [ant0ine/go-json-rest#142]
Hi

I try [api-versioning example](https://github.com/ant0ine/go-json-rest#api-versioning) but it's not work because when request is coming the middleware does execute before extract path parameter.

Thanabodee

**Comment by peterjiz** [comment]
Hi @wingyplus it didn't work for me either, the reason turned out semver wasn't reading the #version number correctly from the URL, I ended up, manually extracting it from the PathParam: 
var versionString string
		if request.PathParam("version") != "" {
			versionString = request.PathParam("version")
		} else {
			toBeExtractedFrom := request.URL.Path
			parts := strings.Split(toBeExtractedFrom, "/")
			versionString = parts[1]
		}

		version, err := semver.NewVersion(versionString)

**Comment by ant0ine** [comment]
I'm sorry, I made a mistake when I converted this example to use the new API. I'm fixing it.

**Comment by ant0ine** [comment]
Should be fixed by https://github.com/ant0ine/go-json-rest-examples/commit/b19b09ad90be5c8697f3eb7b460a9421d5d9a3b3
