### ISSUE TITLE
Test documentation still uses ResourceHandler

### ISSUE THREAD

**Issue by wichert** [ant0ine/go-json-rest#146]
The [test documentation](https://github.com/ant0ine/go-json-rest/blob/master/rest/test/doc.go) still uses the now removed ResourceHandler.

**Comment by ant0ine** [comment]
Thanks for your report! I've just fixed it with this commit: https://github.com/ant0ine/go-json-rest/commit/fc2c9a071db8a007b1d30d171b63af9b7366886c

**Comment by wichert** [comment]
Thanks for the quick response!
