### ISSUE TITLE
rest.Get Undefined?

### ISSUE THREAD

**Issue by jonobattle** [ant0ine/go-json-rest#147]
I'm sure this is a rookie Go user error, but whenever I try the examples I get:

```/main.go:24: undefined: rest.Get```

Or some other error with 'rest. <function name>' undefined.  I can't see where 'rest' is initialised or imported. I'm sure I'm just missing something basic.

Thanks in advance,

J

**Comment by wingyplus** [comment]
Just call `go get -u github.com/ant0ine/go-json-rest/...` and try again
