### ISSUE TITLE
Bad Content-Type or charset, expected 'application/json'

### ISSUE THREAD

**Issue by jixieshi999** [ant0ine/go-json-rest#149]
when i run this command 
```
D:\GOPATH>curl -i -H 'Content-Type: application/json' -v  -d  '{"Code":"FR","Nae":"France"}' http://127.0.0.1:8080/countries
```
it return Bad Content-Type or charset, expected 'application/json'

**Comment by ant0ine** [comment]
I can't reproduce, I'm running the example with `go run countries/main.go`
I get this:

```go
curl -i -H 'Content-Type: application/json'  -d  '{"Code":"FR","Name":"France"}' http://127.0.0.1:8080/countries
HTTP/1.1 200 OK
Content-Type: application/json
X-Powered-By: go-json-rest
Date: Wed, 27 May 2015 07:05:44 GMT
Content-Length: 38

{
  "Code": "FR",
  "Name": "France"
}
```

**Comment by jixieshi999** [comment]
thanks ,my fault,when i replace "'" to """ is OK 
but ,it thow "Error": "invalid character '\\'' looking for beginning of value"
command line 
```
curl -i -H "Content-Type: application/json"     -d '{"Code":"FR","Name":"France"}' http://localhost:8088/countries
```
and thow
```
{
  "Error": "invalid character '\\'' looking for beginning of value"
}
```

**Comment by ant0ine** [comment]
Not sure what's going on with your client, I'd recommend trying another one, or another machine.

**Comment by jixieshi999** [comment]
right,there must be something wrong with my curl environment
because i use java to post data its    ok

**Comment by wqqgt** [comment]
on windows cmd 
like this is ok
curl -i -H "Content-Type: application/json" -d "{\"Code\":\"FR\",\"Name\":\"France\"}" http://localhost:8080/countries
