### ISSUE TITLE
context object per request

### ISSUE THREAD

**Issue by chy168** [ant0ine/go-json-rest#153]
Hi,

May I know if we have any context object in go-json-rest?
In my case, I need to generate a request-id for my logger.

Scenario might be, once go-json-rest receive a request, a middleware will generated a UUID as the request-id. Any function in this request can retrieve this request-id (ex: write log with request-id).

How can I store the request-id in each request?

**Comment by ant0ine** [comment]
Yes, it's named `Request.Env`.
