### ISSUE TITLE
Add io.Writer interface to ResponseWriter 

### ISSUE THREAD

**Issue by dingoxiong** [ant0ine/go-json-rest#155]
type ResponseWriter interface {
        // io.Writer interface ,  add this line
	Write(b []byte) (int, error)
}

It is useful for other libs, write data to response with io.Writer.

**Comment by ant0ine** [comment]
I think you need a type assertion: 

`writer := w.(http.ResponseWriter)`

**Comment by dingoxiong** [comment]
ok, maybe interface is better :)
