### ISSUE TITLE
Content-Type header must set charset in response

### ISSUE THREAD

**Issue by wichert** [ant0ine/go-json-rest#156]
Currently the response does not include a charset hint in the Content-Type header, which can cause a client to think something other than UTF-8 is used for the response. To fix this the response should do something like this:

```go
w.Header().Set("Content-Type", "application/json; charset=UTF-8")
```

**Comment by ant0ine** [comment]
I think this should not be necessary. Per spec, the default encoding of JSON is UTF8.

Any example of client thinking otherwise ?

**Comment by wichert** [comment]
Most obvious thing is that it breaks a quick tests in the browser: at least Chrome seems to think the result is ISO-8859-1 when it displays content. I suspect there are some frameworks that historically default to assuming that encoding as well, and layer JSON decoding on top of that and so might break as well.

Is there any harm in always explicitly defining the charset?

**Comment by kimxilxyong** [comment]
I have the same problem, when the charset is not manually set to utf-8 in the Content-Type, the german "umlauts" like Ä Ü Ö are not displayed correct in Chrome and Firefox.

Screenshot if not setting the charset:
![rest_default](https://cloud.githubusercontent.com/assets/11922186/8390965/5d283944-1cae-11e5-8df6-3820b57744a3.png)

Screenshot if "manually" setting the charset in every handler func:
```go
w.Header().Set("Content-Type", "application/json; charset=utf-8")
```
![rest_utf8](https://cloud.githubusercontent.com/assets/11922186/8390974/cfeb3102-1cae-11e5-8c5f-52f2b5ba44a2.png)

I think that a Default Charset string added to Api or Router could be the easiest solution. Or would it be better to add a MiddleWare setting the charset in the Header?

**Comment by pior** [comment]
Chrome may not be the first client of a REST framework, and this may be correct regarding the spec, but the Robustness principle (Be conservative in what you send, be liberal in what you accept) suggests that setting the charset is a good idea.

**Comment by ant0ine** [comment]
Fixed. https://github.com/ant0ine/go-json-rest/commit/3152f30bb246f193be132e9d14e6e4ad174eed50

```
Include charset=utf-8 in the JSON response.

Per spec, UTF-8 is the default, and the charset parameter should not
be necessary. But some clients (eg: Chrome) think otherwise.
Since json.Marshal produces UTF-8, setting the charset parameter is a
safe option.

This changeset also includes a better ContentTypeIsJson test method.
It expects the charset to be utf-8 or not set.
```
