### ISSUE TITLE
Fallback all not-defined requests to 404

### ISSUE THREAD

**Issue by kkszysiu** [ant0ine/go-json-rest#157]
Hello,

Is there possibility to return 404's for all requests that we're not defined?
I can handle it by standard Go http module probably but I'm just curious is there better way to do it.

**Comment by wingyplus** [comment]
@kkszysiu what do you want to handle 404 request?  because default of go-json-rest return http status 404 after find route at this [line](https://github.com/ant0ine/go-json-rest/blob/master/rest/router.go#L47).

**Comment by ant0ine** [comment]
Agreed with @wingyplus, if you use the Router, then you should get 404 or 405 generated for you if no route is found. Can I close the issue ?

**Comment by kkszysiu** [comment]
Yeap. My fault. I had badly configured Nginx, which was trying to intercept those error codes.
