### ISSUE TITLE
[enhancement]how about develop a generator, to generate a .raml file from router, or generate .go code from .raml

### ISSUE THREAD

**Issue by ryanemax** [ant0ine/go-json-rest#158]
[enhancement]how about develop a generator, to generate a .raml file from router, or generate .go code from .raml

Is there any plan to do this?
I've already used a tool to generate Angularjs .js for front-end , and think I want one for back-end.
hoping. :)

**Comment by ryanemax** [comment]
There is one to generate document/html, https://github.com/gtrevg/golang-rest-raml-validation
,but not backend code.

**Comment by ant0ine** [comment]
Hi,

There are many ways and many competing formats for generating the server code. Raml, Swagger, JSON Schema/Hyperschema.

I'm more and more interested in JSON Schema/Hyperschema (http://json-schema.org/) and I was thinking about writing a generator. I also think this should be a different package, possibly even a different repository.

Stay tuned.

**Comment by ryanemax** [comment]
Thx, I'll try JSON Schema/Hyperschema.
