### ISSUE TITLE
Recorded.ContentTypeIsJson performs invalid assertion

### ISSUE THREAD

**Issue by viktorasm** [ant0ine/go-json-rest#160]
I'm explicitly stating charset in my service response, and `Recorded.ContentTypeIsJson` does not like it:
```
Content-Type: application/json expected, got: application/json; charset=UTF-8
```

**Comment by wingyplus** [comment]
@ant0ine It relate to issue #156 ?

**Comment by viktorasm** [comment]
relates a bit, but from a different angle.
In my API, I'm overriding the default content-type with "application/json; charset=UTF-8", for few reasons outlined in #156 ; however, I would still would expect that test assertion would qualify this as valid Json content type, which it currently does not.

**Comment by ant0ine** [comment]
Fixed. https://github.com/ant0ine/go-json-rest/commit/3152f30bb246f193be132e9d14e6e4ad174eed50

```
Include charset=utf-8 in the JSON response.

Per spec, UTF-8 is the default, and the charset parameter should not
be necessary. But some clients (eg: Chrome) think otherwise.
Since json.Marshal produces UTF-8, setting the charset parameter is a
safe option.

This changeset also includes a better ContentTypeIsJson test method.
It expects the charset to be utf-8 or not set.
```
