### ISSUE TITLE
Why not support optional params in routing？

### ISSUE THREAD

**Issue by applee** [ant0ine/go-json-rest#161]
I do not like to write tow routing like:
/folder
/folder/:fid

Because if fid is empty, it means list the default folder, otherwise, list the specified. And many other framework support this feather like:
/folder/(:fid)

**Comment by karen2k** [comment]
Nice feature, but regarding the idea of REST, `GET /folder` should response with a list of objects. `GET /folder/:fid` should response with and object though.
So you should have two different controllers/actions for that.

What's the use case to mess these two routes up?

**Comment by applee** [comment]
Thanks for much, I also agree with u right now, tow handlers seems are necessary.
