### ISSUE TITLE
Custom Error JSON Format

### ISSUE THREAD

**Issue by RichardKnop** [ant0ine/go-json-rest#164]
Is it possible to customise error JSON format?

All I want to do is to change `Error` to lowercase `error`. So when in my code I do:

```go
rest.Error(w, "Decode JSON error", http.StatusBadRequest)
```

I'd like to get this JSON:

```json
{
  "error": "Decode JSON error"
}
```

**Comment by railsmechanic** [comment]
+1

**Comment by ant0ine** [comment]
I made a mistake by not having “Error” in lower case. But I also have a strict rule of not breaking compatibility between major versions (see semver.org).
One solution could be to have a global variable with a default value for the error payload field. This default will be “Error” for compat reason, but you’ll be able to change it for your project.
This whole thing will then be cleaned up for version 4.
Sounds reasonable ?

**Comment by ant0ine** [comment]
done https://github.com/ant0ine/go-json-rest/commit/c3c57b2a42c1c77a2d8cb5d66393d8796f42cfc0

**Comment by railsmechanic** [comment]
:+1:
