### ISSUE TITLE
Need a function that returns the JSON generated by WriteJson()

### ISSUE THREAD

**Issue by nithin-bose** [ant0ine/go-json-rest#170]
There are cases like caching of the response which needs the generated JSON. Is there a way to access this at the moment? 

The way I am doing this write now is to marshal the response object manually and then pass the response object to WriteJson for rendering, which essentially does the same thing. This seems to be redundant.

**Comment by ant0ine** [comment]
You can do what `WriteJson` does:

```
	b, err := w.EncodeJson(v)
	_, err = w.(http.ResponseWriter).Write(b)
```

**Comment by nithin-bose** [comment]
Sorry I was away for a few days. That would do. Thanks
