### ISSUE TITLE
CORS Middleware & rest.Error

### ISSUE THREAD

**Issue by letmejustfixthatohitsbroken** [ant0ine/go-json-rest#178]
Hi,
I'm using your awesome package for a little project. How ever, I'm developing the server in go and the client in angular2. To be able to communicate with the server I'm using the CORS Middleware. Whenever the server answers with 
```Go
    // w rest.ResponseWriter
    rest.Error(w, "error", http.StatusBadRequest)
```
the additional header aren't sent. Is this a bug or a feature (I'm not too deep into http protocol, but I suppose the headers are missing since I don't see any reason why they shouldn't be sent in case of a bad request or any other error).

**Comment by ant0ine** [comment]
Hi,
Thanks for your report. I wrote the CORS middleware a while ago, but looking at it now, it seems that all the extra headers are written before the wrapped middleware is called: this line: https://github.com/ant0ine/go-json-rest/blob/master/rest/cors.go#L132

So, writing and error with rest.Error(...) should not skip any header.

Would you mind sending a code snippet that reproduce the bug ? That will be easier to track for me.

Antoine

**Comment by letmejustfixthatohitsbroken** [comment]
Hi,
thanks for your quick answer. Here's the code snippet were I setup the REST-servre:

```Go
jwt := &jwt.JWTMiddleware{
    Key:           []byte("secret key"), // TODO: Randomize key on startup
    Realm:         "my-auth-realm",
    Timeout:       time.Hour,
    MaxRefresh:    time.Hour * 24,
    Authenticator: controller.AuthenticateUser,
    PayloadFunc:   controller.AuthenticateUserSetPayload,
}
s.Api.Use(&rest.IfMiddleware{
    Condition: func(request *rest.Request) bool {
    // Allow pre-flight OPTIONS requests and the login
    return request.Method != "OPTIONS" && request.URL.Path != "/login"
		},
		IfTrue: jwt,
})
s.Api.Use(&rest.CorsMiddleware{
    RejectNonCorsRequests: false,
    AllowedMethods:        []string{"GET", "POST", "OPTIONS"},
    OriginValidator: func(origin string, request *rest.Request) bool {
        // allow every origin (for now)
        return true
    },
    AllowedHeaders:                []string{"access-control-allow-credentials", "access-control-allow-headers", "access-control-allow-methods", "access-control-allow-origin", "authorization", "content-type"},
    AccessControlAllowCredentials: true,
})
// Setup router
router, _ := rest.MakeRouter(
    // Test connectivity
    rest.Get("/ping", controller.Ping),
    rest.Post("/login", jwt.LoginHandler),
    rest.Get("/login_refresh", jwt.RefreshHandler),
    [...]
)
s.Api.SetApp(router)
```

I just double checked everything. And it seems like that only the Unauthorized errors are the problem (which are raised by the JWTMiddleware). So this may be a problem in the JWTMiddleware and not the rest api?!

**Comment by ant0ine** [comment]
I see. The order of the middlewares matters. I think that if you put CORS first, the JWT error response will have the right headers.

**Comment by letmejustfixthatohitsbroken** [comment]
aye, that did the trick. Good to know (maybe this should be mentioned somewhere in the docs?). Thanks a lot
