### ISSUE TITLE
Broken connections & Streaming API

### ISSUE THREAD

**Issue by letmejustfixthat** [ant0ine/go-json-rest#180]
I'm building a chat App. I'm writing the server in Go & (this) REST package and a client in Angular2. I'm using the [streaming ](https://github.com/ant0ine/go-json-rest#streaming) part to build a message broker (or push service). To do so I'm using [oboe](http://oboejs.com) on client side. This works basically fine, how ever, the server won't recognize broken connections to clients. Since I want the users to be able to be online with different clients (like web version and a mobile app) I implemented a message broker with `n` broker-channels per user. Every time the client loses the connection (or when the web version is refreshed with F5) the client will establish a new connection. And this leads to tons of dead connections. How am I able to check if a connection is alive or not? Have some code:
```Go
func (b *Broker) Listen(user models.User, w rest.ResponseWriter, r *rest.Request) {
	// Make channel
	b.Init()
	var addedSlot int
	if b.listeners[user.UID] == nil {
		b.listeners[user.UID] = append(b.listeners[user.UID], make(chan *models.BrokerMessage))
	} else {
		// no sure what happens to dead channels -> iterate
		foundFreeChannel := -1
		for i, c := range b.listeners[user.UID] {
			if c == nil {
				foundFreeChannel = i
				addedSlot = i
				c = make(chan *models.BrokerMessage)
			}
		}
		if foundFreeChannel < 0 {
			b.listeners[user.UID] = append(b.listeners[user.UID], make(chan *models.BrokerMessage))
			addedSlot = len(b.listeners[user.UID]) - 1
		}
	}
    
    // HTTP Headers 
	w.(http.Flusher).Flush()
    
        // this is never reached
	defer b.unregisterListener(addedSlot, user.UID)

	for {
		m, ok := <-b.listeners[user.UID][addedSlot]
		// log.Println("received message for user " + user.Name)        
		if !ok { // This never triggers since unregisterListener is never called
			log.Println(fmt.Sprintf("channel's not ok, closing [%s][%d]", user.UID, addedSlot))
			return
		}
		// Marshal
		str, err := json.Marshal(m)
		if err != nil {
			log.Println("error sending message to broker, marshalling failed: " + err.Error())
			continue
		}
		i, err := w.(http.ResponseWriter).Write(str)
		w.(http.Flusher).Flush()      
        
        // always the same value, if the connection is still alive or not
        log.Println("sent bytes: ", i)
        
        if err != nil {
            log.Println("broker channel dead, bytes written", i, err)
            return
        }
	}
}
```

Here some example output: (4 connections dead, 1 alive)

```
2016/02/09 19:55:23 sent bytes:  186
2016/02/09 19:55:23 sent bytes:  186
2016/02/09 19:55:23 sent bytes:  186
2016/02/09 19:55:23 sent bytes:  186
2016/02/09 19:55:23 sent bytes:  186
```

Sometimes, but I have no idea under what conditions, I get a broken pipe (what I would expect imediatly after the connection was closed or the next message is send):
```
2016/02/09 20:01:42 broker channel dead, bytes written 0 write tcp xx.xx.xx.xx:43021: broken pipe
2016/02/09 20:01:42 closing broker channel for userID 1 0
```

Do you have an idea what's going on? Is there just something like a timeout of 20 minutes? Or is there another way to check if the connection is still alive & healthy?

**Comment by thetooth** [comment]
The go-json-rest isn't really setup for continuous connections, neither is plain HTTP a good way of doing this. I would look at using websockets or a plain TCP connection that has explicit lifetime control.

However if you still wish to use this approach since it's the simplest you'll need to handle the close event. The std lib has CloseNotifier which "This mechanism can be used to cancel long operations on the server if the client has disconnected before the response is ready.".

```go
func (b *Broker) Listen(user models.User, w rest.ResponseWriter, r *rest.Request) {
	// Make channel
	b.Init()
	var addedSlot int
	if b.listeners[user.UID] == nil {
		b.listeners[user.UID] = append(b.listeners[user.UID], make(chan *models.BrokerMessage))
	} else {
		// no sure what happens to dead channels -> iterate
		foundFreeChannel := -1
		for i, c := range b.listeners[user.UID] {
			if c == nil {
				foundFreeChannel = i
				addedSlot = i
				c = make(chan *models.BrokerMessage)
			}
		}
		if foundFreeChannel < 0 {
			b.listeners[user.UID] = append(b.listeners[user.UID], make(chan *models.BrokerMessage))
			addedSlot = len(b.listeners[user.UID]) - 1
		}
	}

	// HTTP Headers 
	w.(http.Flusher).Flush()

	// this is never reached
	defer b.unregisterListener(addedSlot, user.UID)
	
	// Check if we can get a closed event, HTTP1.0 will fail everytime
	cn, ok := w.(http.CloseNotifier)
	if !ok {
		http.Error(w, "cannot stream", http.StatusInternalServerError)
		return
	}

	for {
		select {
		case <-cn.CloseNotify(): // Listen for close event and return
			log.Println("done: closed connection")
			return
		case m, ok := <-b.listeners[user.UID][addedSlot]:
			// log.Println("received message for user " + user.Name)        
			if !ok { // This never triggers since unregisterListener is never called
				log.Println(fmt.Sprintf("channel's not ok, closing [%s][%d]", user.UID, addedSlot))
				return
			}
			// Marshal
			str, err := json.Marshal(m)
			if err != nil {
				log.Println("error sending message to broker, marshalling failed: " + err.Error())
				continue
			}
			i, err := w.(http.ResponseWriter).Write(str)
			w.(http.Flusher).Flush()

			// always the same value, if the connection is still alive or not
			log.Println("sent bytes: ", i)

			if err != nil {
				log.Println("broker channel dead, bytes written", i, err)
				return
			}
		}
	}
}
```

**Comment by letmejustfixthat** [comment]
Thanks for you answer - I have no time to test this right now, but I'm going to give some feedback on the solution later. How ever. 
I'd like to discuss the approach, as you think it is "just the easiest". Why should I not use HTTP and the REST API? Here some reasons why I think this approach is the best (AND the easiest)

1. It's the easiest approach ;-)
2. Never add complexity, where no additional complexity is required (Sockets). It makes software error prown
--> Using sockets would add complexity to the server AND the client. Just another REST endpoint is less code, less documentation, less error sources, ... less complexity. 
----> And therefore cheaper (think of GUI developers who don't need to know anything about Sockets or connection life cycles or whatever. They just connect to a REST endpoint and get their push service)
--> Almost every potential (if not every) client-platform out there speaks HTTP out of the box
3. In many cases, like this one, there is no such thing as a "real" life-cycle management required. The only thing needed is the underlying TCP/IP guarantee, that a package has been delivered to a client (or not)
--> which is not the case here and we are breaking the ISO/OSI model idea (why not use UDP then and be faster)
--> Mobile use cases will hardly have constant connections but a lot a re-connects since 
connections are unstable by nature

**Comment by letmejustfixthat** [comment]
Hi again, 
sorry for the late answer. Your solution works so far (altough something is still broken, but the approach seems to be working). I only had to change one thing:

    // Check if we can get a closed event, HTTP1.0 will fail everytime
    cn, ok := w.(http.CloseNotifier)
    if !ok {
        rest.Error(w, "cannot stream", http.StatusInternalServerError)
        return
    }

( `rest.Error(...)` instead of `http.Error` )
