### ISSUE TITLE
JSON payload is empty

### ISSUE THREAD

**Issue by rcholic** [ant0ine/go-json-rest#203]
I have this model struct:
```
type Todo struct {
	id   int
	name string
}
```
And I am trying to do a POST request to create an object of `Todo` type:
```
body, _ := ioutil.ReadAll(r.Body)
log.Println("body content is: ", string(body)) // here I can see {"name": "test1"}
var todo Todo = Todo{}
err := r.DecodeJsonPayload(&todo) // here the error shows JSON payload is empty
```

However, in the console of the POSTMAN client, the error shows:

```
{
  "Error": "JSON payload is empty"
}
```

I was wondering where might go wrong. Thanks

**Comment by ajpen** [comment]
`body, _ := ioutil.ReadAll(r.Body)` will read everything from the body. When you do `err := r.DecodeJsonPayload(&todo) ` after, theres nothing left in the body and so todo will be blank.
