### ISSUE TITLE
Export router

### ISSUE THREAD

**Issue by vaudoc** [ant0ine/go-json-rest#21]
If I understand correctly, you abandoned the go-urlrouter package and its code continues to evolve here.

While this package is great for its use case, I think, it is unfortunate, that now the router is unusable by itself for people who use their own resource handlers.

Thus, could you make the router available again by exporting its values and methods just like in go-urlrouter.

Thanks. Great work.

**Comment by ant0ine** [comment]
v3 has interchangeable app/router.
