### ISSUE TITLE
test.MakeSimpleRequest() sets gzip encoding but doesn't do decompression

### ISSUE THREAD

**Issue by joeshaw** [ant0ine/go-json-rest#214]
The `test.MakeSimpleRequest` function explicitly sets the `Accept-Encoding: gzip` header.  The standard library client already automatically sets `Accept-Encoding: gzip` and does decompression transparently.  Setting it explicitly makes it the responsibility of the caller to do decompression, and `MakeSimpleRequest` doesn't, which breaks any tests that use it.

I think the solution is simply to remove the `r.Header.Set("Accept-Encoding", "gzip")` call in `MakeSimpleRequest`.  Code that calls `ContentEncodingIsGzip` should continue to work.

**Comment by joeshaw** [comment]
Oh, it looks like `Accept-Encoding: gzip` isn't being set automatically because it's not going through the `Transport` stuff -- it's going via the `httptest.ResponseRecorder`.  So setting the header explicitly is the right thing to do, but I still think that the body should be transparently replaced with a decompressed version when `Content-Encoding: gzip` is found in the response.

**Comment by ant0ine** [comment]
Thanks @athomason for the fix!
