### ISSUE TITLE
Websocket example

### ISSUE THREAD

**Issue by kronos** [ant0ine/go-json-rest#25]
I can't make the library works with standart websocket package.

**Comment by vidario** [comment]
I'm also trying to get websockets working. I'm not that well versed in go, so forgive me if it's easy.

I'm using gorilla websockets, which requires (w http.ResponseWriter and, r *http.Request)

Unfortunately, I can not seem to figure out how to pass on a *rest.Request as a *http.Request

socket(w.(http.ResponseWriter), ???)

Anyone got an idea what to do?

Thank you for the attention.

**Comment by vidario** [comment]
I figured it out. I let MakeHandler handle the "/" (main api) and websockets on e.g. "/ws"

~~~go
    http.Handle("/", api.MakeHandler())   // API
    http.Handle("/ws/", http.StripPrefix("/ws", wsHandler)   // WebSockets
    log.Fatal(http.ListenAndServe(host + ":" + port, nil))  // Handle both

**Comment by wingyplus** [comment]
@vidario you can change type from rest.ResponseWriter to http.ResponseWriter with type assertion. And *rest.Request has a *http.Request embed in struct you can use request.Request to get *http.Request.

**Comment by ant0ine** [comment]
Agreed, it's easy to get back to the net/http objects. Request is compatible, and responseWriter just needs a type assertion.

Any volunteer to share your experience as an example in https://github.com/ant0ine/go-json-rest-examples/ ? 

Antoine

**Comment by wingyplus** [comment]
@ant0ine I send pr to go-json-rest-examples repo here https://github.com/ant0ine/go-json-rest-examples/pull/12 .

**Comment by ant0ine** [comment]
Thanks @wingyplus! Great example!
