### ISSUE TITLE
Modify rest.Error Output?

### ISSUE THREAD

**Issue by rdegges** [ant0ine/go-json-rest#71]
Heyo! I'm sort of a go newbie, so hopefully this isn't a stupid question -- but how could I go about changing the rest.Error(...) JSON payload?

Right now, if I use rest.Error it returns a JSON dict that looks like this:

{"Error": "..."}

I'd like to make the "Error" string lowercase ("error") to be more consistent with the rest of my API.

Thanks!

**Comment by sebest** [comment]
I do agree with the case that it should be "error" and not "Error", the fact that GoLang use capital for public fields is something that should not be "visible" from a Rest API point of view.
And using camelCase for Rest API is the most common pattern:
https://blog.apigee.com/detail/restful_api_design_what_about_attribute_names
