### ISSUE TITLE
Post can't handle form-data?

### ISSUE THREAD

**Issue by mgleason** [ant0ine/go-json-rest#94]
I'm using POSTMAN to test the api's of the "Gorm" example.  Posting raw JSON to reminders does work (posted {"Message":"This is a test"} to http://127.0.0.1:8080/reminders).

But, posting form-data with any key/value combination to reminders () returns the following error:

``` javascript
{
Error: "invalid character '-' in numeric literal"
}
```

Posting key: Message   Value:This is a test   as x-www-form-urlencoded returns:

``` javascript
{
Error: "invalid character 'm' looking for beginning of value"
}
```

POSTMAN is the Chrome-app.  Tried another Chrome add-in called "Advanced Rest Client" and reminders () returns the same error: 

``` javascript
{
Error: "invalid character 'M' looking for beginning of value"
}
```

**Comment by boonep** [comment]
I had to interface with a third-party application that would could only post "application/x-www-form-urlencoded" data.  I created a middleware to convert the body data to JSON for this one specific endpoint to work with the rest of my app based on this framework.  

You can check it out here: https://github.com/boonep/go-json-rest-middleware-formjson 

Thanks!

**Comment by charmila22** [comment]
{
Error: "invalid character '-' in numeric literal"
}

how do i overcome this error
